Help the caller along if a malformed URI is used to make an HTTP request.
We had problems where we gave a cryptic error when the user's request
URL like "www.example.org/api/json/get_stuff" is interpretted as a relative
path rather than a fully qualified address:
  java.lang.IllegalStateException: Target host must not be null, or set in parameters.

The new message breaks the address into parts to make this more clear:
  java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=www.example.org/api/json/get_stuff

Change-Id: Ie102718dc15b92d68835f1c34b538639f500eeaa
http://code.google.com/p/android/issues/detail?id=9929